# -*- coding: utf-8 -*-
"""advanced visuals

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1guoMgFVdKeHDmTpkLLiVrZvkcBlEGKdY
"""



"""##**1. What is the difference between a Basic Filter, Advanced Filter, and a Slicer in Power BI?**

## Difference between Basic Filter, Advanced Filter, and Slicer in Power BI

- Basic Filter:

It is the simplest filter. You just select the values you want to show in the report. For example, selecting only 2023 from a list of years.

Advanced Filter:

It is used when you want to apply conditions like greater than, less than, contains, etc. For example, showing sales greater than ₹50,000.

Slicer:

A slicer is a visual filter that appears on the report page. Users can click options (like Region or Product) and the visuals update instantly.

#**4. What is a Visual-Level Filter, and how does it differ from Page-Level and Report-Level Filters?**

# - Visual-Level Filter vs Page-Level Filter vs Report-Level Filter

**Visual-Level Filter:**

This filter works only on a single visual.

**Page-Level Filter:**

This filter applies to all visuals on the same page.

**Report-Level Filter:**

This filter affects all pages and visuals in the entire report.

#**10. Explain the difference between Drill-Down and Drill-Through in Power BI using a real-world example.**

# Difference between Drill-Down and Drill-Through (Real Example)

- Drill-Down:

Used to go deeper into the same visual.
Example:
Sales → Year → Quarter → Month.

Drill-Through:

Used to open another page with detailed information.
Example:
Clicking a product to open a page showing its sales by region and time.

#**13. What is the “Keep All Filters” option in Drill-Through? How does it affect user interaction**

- The Keep All Filters option keeps all the filters from the previous page when you move to the drill-through page.

Example:
If the user selected Region = North and Year = 2023, the drill-through page will also show North region and 2023 data.

This helps maintain context and better analysis.

"""